# Site settings
title: Luis Parra
description: Welcome to my Website
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://checoparraluis.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Luis Parra
user_description: I am InfoSec enthusiast and a wanna-be Software Engineer.
user_title: Data Analyst / Data Scientist
email: ChecoParraLuis@gmail.com

github_username:  checoparraluis
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
