# Site settings
title: inc0gnit0
description: Welcome to my Website
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iinc0gnit0.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: inc0gnit0
user_description: I am InfoSec enthusiast and a wanna-be Software Engineer.
user_title: InfoSec Enthusiast
email: iinc0gnit0@pm.me
twitter_username: iinc0git0
github_username:  iinc0gnit0
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
